humanwhocodes/mentoss

src/fetch-mocker.js
tests/fetch-mocker.test.js

This pull request introduces support for aborting fetch requests in the `FetchMocker` class and includes corresponding tests to ensure this functionality works as expected.
* Added logic to check if a fetch request has been aborted and to handle abort events by throwing an appropriate error (`src/fetch-mocker.js`).
* Included global definitions for `AbortSignal`, `queueMicrotask`, and `AbortController` in the test file (`tests/fetch-mocker.test.js`).
* Added a new test suite to verify that `FetchMocker` correctly handles aborted fetch requests, including both immediate and delayed abort scenarios (`tests/fetch-mocker.test.js`).

feat: Support AbortSignal in fetch()

---

src/request-matcher.js
tests/mock-server.test.js

This pull request introduces support for handling `ArrayBuffer` bodies in the `RequestMatcher` class and updates related tests in `tests/mock-server.test.js`. The most important changes include adding logic to compare `ArrayBuffer` bodies, updating the `createRequest` function in the tests to handle `ArrayBuffer` bodies, and adding new tests to verify the functionality.
* Added logic to compare `ArrayBuffer` bodies, including checks for byte length and individual byte values.
* Added a console log statement for debugging purposes.
* Modified `createRequest` to handle `ArrayBuffer` bodies and set the appropriate `content-type` header.
* Updated global variables to include `TextEncoder` for encoding text into `ArrayBuffer`.
* Enhanced `getResponseBody` to handle `arrayBuffer` responses.
* …

fix: Ensure request ArrayBuffer body works

---

src/cors.js
src/fetch-mocker.js
tests/fetch-mocker.test.js

This pull request introduces a new `CorsError` class to handle CORS-related errors more effectively and updates various parts of the codebase to use this new error class. The most important changes involve refactoring existing error handling to use `CorsError` and updating tests accordingly. This ensures that CORS errors all follow the same uniform messaging.
* [`src/cors.js`](diffhunk://#diff-e7461d918b27ad31cebeb3be2f2e87fe5b8fea3d353077eefbb6d82a7644f4f4R90-R111): Added the `CorsError` class to represent errors that occur when a CORS request is blocked.
* [`src/cors.js`](diffhunk://#diff-e7461d918b27ad31cebeb3be2f2e87fe5b8fea3d353077eefbb6d82a7644f4f4L101-R134): Updated the `assertCorsResponse` function and methods in the `CorsPreflightData` class to throw `CorsError` instead of …

refactor: Normalize CORS errors

---

src/http.js
src/mock-server.js
src/types.ts
tests/mock-server.test.js

This pull request includes various updates to the `MockServer` class and related files to improve input validation both at runtime and at development time. The most important changes include the addition of new validation functions, updates to route methods to use methodless request pattern types, and enhancements to the test suite. This ensures that both request and response patterns are valid before registering them.
* [`src/mock-server.js`](diffhunk://#diff-5024b7448f56bf978cf6ef5e933780ebabaf2d2977e6650c3c4df42c484245c4R75-R124): Added `assertNoMethod` and `assertValidResponsePattern` functions to validate request patterns without methods and response patterns, respectively.
* [`src/mock-server.js`](diffhunk://#diff-5024b7448f56bf978cf6ef5e933780ebabaf2d2977e6650c3c4df42c484245c4L40-R4 …

fix: Validate route inputs

---

docs/src/content/docs/mock-servers/extended-response-patterns.mdx
src/fetch-mocker.js
src/mock-server.js
src/types.ts
tests/fetch-mocker.test.js
tests/mock-server.test.js

This pull request introduces the ability to delay responses in the mock server and includes several related changes across the codebase. The most important changes include updates to the documentation, modifications to the `MockServer` and `Route` classes, and adjustments to the tests to account for the new delay feature.
* Added the `delay` key to the response pattern object in the documentation to explain how to delay responses by a specified number of milliseconds. [[1]](diffhunk://#diff-b2b70c9e8cc68f67af3f7f6832092e0c4972402451b3196650683499f7427dcaR15) [[2]](diffhunk://#diff-b2b70c9e8cc68f67af3f7f6832092e0c4972402451b3196650683499f7427dcaR100-R116)
* Added the `delay` property to the `ResponsePattern` interface in `src/types.ts` to define the delay duration for responses.
* …

feat: Add ability to delay generating a response

---

docs/src/content/docs/fetch-mockers/testing-helpers-fetch-mocker.mdx
docs/src/content/docs/mock-servers/testing-helpers-mock-server.mdx
src/fetch-mocker.js
src/mock-server.js
tests/fetch-mocker.test.js
tests/mock-server.test.js

This pull request introduces new testing helpers for the `FetchMocker` and `MockServer` classes, as well as updates to their documentation. The most important changes include the addition of methods to verify route calls, check for uncalled routes, and clear routes for reuse in tests. Additionally, there are several updates and new tests to ensure the functionality of these helpers.
* Added new documentation files for `FetchMocker` and `MockServer` testing helpers, detailing methods such as `allRoutesCalled`, `assertAllRoutesCalled`, `called`, `uncalledRoutes`, and `clearAll` (`docs/src/content/docs/fetch-mockers/testing-helpers-fetch-mocker.mdx` [[1]](diffhunk://#diff-d55e5a2d1819ef409603f373660be06cd5a4fc29a7e3d8d7124ccfe5a336fea6R1-R146) …

feat: Add test helper methods

---

src/fetch-mocker.js
tests/fetch-mocker.test.js
tests/mock-server.test.js

This pull request implements changes to make Mentoss work in Bun. To do so, I had to workaround a couple of bugs that are present in Bun's `fetch` implementation:
https://github.com/oven-sh/bun/issues/17052
https://github.com/oven-sh/bun/issues/17085
Improvements to fetch requests:
* [`src/fetch-mocker.js`](diffhunk://#diff-09d3018654f9d696c2ce0a5938eb9b5dd6adb822704efafcbfde8b6342f246c5R194-R209): Added a workaround to handle Bun's fetch implementation that sets credentials to "include" by default and doesn't allow overwriting that value when creating a Request.
Improvements to tests:
* [`tests/fetch-mocker.test.js`](diffhunk://#diff-c7749aa975a360a952d495ce66db5a38c09de5fa882d6cf00f2a86949208c1b9L535-R535): Simplified the error message assertion in the `FetchMocker` test to use a …

fix: Make Mentoss work in Bun

---

bun.js
docs/src/content/docs/fetch-mockers/mocking-browser-requests.mdx
docs/src/content/docs/fetch-mockers/mocking-cors-requests.mdx
src/cookie-credentials.js
src/cors.js
src/fetch-mocker.js
src/index.js
src/mock-server.js
src/types.ts
src/util.js
tests/cookie-credentials.test.js
tests/fetch-mocker.test.js
tests/mock-server.test.js

This pull request includes updates to the documentation for mocking browser requests using Mentoss, focusing on handling credentialed requests and CORS (Cross-Origin Resource Sharing) requests. The most important changes include restructuring the documentation, adding new sections, and providing detailed examples.

feat: Mocking credentialed requests

---

src/custom-request.js
src/fetch-mocker.js
tests/custom-request.test.js

This pull request introduces a new custom request class to enhance control over requests and includes corresponding updates to the `FetchMocker` class and test coverage. This allows me to both add info to requests (such as `id` to track requests through cloned `Request` objects) and to address runtime-specific bugs such as Bun and Deno's lack of supporting the `credentials` property.
* [`src/custom-request.js`](diffhunk://#diff-3d024b2982939484b878c8446a661b479428d7e4bc40a72140164c7ef7ce0cb9R1-R70): Added a new `createCustomRequest` function that generates a custom request class extending the standard `Request` class. This custom class includes unique IDs for each request, ensures the ID is immutable, and handles credentials compatibility across different runtimes.
* …

refactor: Custom request class

---

.github/workflows/release-please.yml
package-lock.json
package.json
tools/social-post.js

This pull request introduces a new feature of the release process that automates the creation of social media posts for new releases using OpenAI's API. The changes include updates to the workflow configuration, the addition of a new dependency, and a new script for generating the social media posts.
* [`.github/workflows/release-please.yml`](diffhunk://#diff-2c84033033d49186c63e6adcd705f63b11ae6814cd76c152c9c486d389fbccf3R56-R63): Added steps to generate a social media post using `tools/social-post.js` and update the release announcement tweet to use the generated post.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L66-R67): Added the `openai` package as a new dependency and updated the `mocha` package to version 11.0.0.
* …

ci: Include social post summarizer

---

src/util.js
tests/mock-server.test.js

This pull request includes changes to enhance the handling of request bodies in the `getBody` function and adds a new test case to ensure proper functionality when a JSON request is sent without a body.
fixes #48
* [`src/util.js`](diffhunk://#diff-9c0ec1b0a889e599f3ff81590864dd9dc65684a86b41f1da75acc53fafed12e3L97-R98): Modified the `getBody` function to be asynchronous and improved handling of cases where the request body is empty. [[1]](diffhunk://#diff-9c0ec1b0a889e599f3ff81590864dd9dc65684a86b41f1da75acc53fafed12e3L97-R98) [[2]](diffhunk://#diff-9c0ec1b0a889e599f3ff81590864dd9dc65684a86b41f1da75acc53fafed12e3R107-R117)
* [`tests/mock-server.test.js`](diffhunk://#diff-8ea18cf1c7d7bb1ad2967a064ede011cc0f2b983f81dc73877857d6b379049dfR566-R588): Added a new test case to verify that the …

fix: Request without a body should not throw an error

---

src/cors.js
src/fetch-mocker.js
tests/cors.test.js
tests/fetch-mocker.test.js

This pull request introduces a new function to handle non-simple headers in CORS requests and updates the `FetchMocker` class to use this function. Additionally, it includes comprehensive tests for the new functionality.
* [`src/cors.js`](diffhunk://#diff-e7461d918b27ad31cebeb3be2f2e87fe5b8fea3d353077eefbb6d82a7644f4f4R394-R431): Added the `getNonSimpleHeaders` function to identify headers that are not allowed in a CORS simple request. This function checks for special cases like the `Range` and `Content-Type` headers and ensures they are validated correctly.
* [`src/fetch-mocker.js`](diffhunk://#diff-09d3018654f9d696c2ce0a5938eb9b5dd6adb822704efafcbfde8b6342f246c5L360-R380): Updated the `FetchMocker` class to use the `getNonSimpleHeaders` function when creating a preflight request. This …

fix: Limit Access-Control-Request-Headers to unsafe headers only

---

src/custom-request.js
src/fetch-mocker.js
src/mock-server.js
tests/custom-request.test.js
tests/fetch-mocker.test.js
tests/mock-server.test.js

This pull request ensures that the `Response#mode` property is properly set to `"cors"` when the `type` property of the `Request` is set to `"cors"`. This also ensures that the default `Response#mode` is `"cors"` per the Fetch API specification (Bun sets it to `"default"`.
The most important changes include setting the `mode` property correctly in the `createCustomRequest` function, updating the `FetchMocker` class to set response properties, and modifying the `MockServer` tests to validate response status and type.
Replaces and closes https://github.com/humanwhocodes/mentoss/pull/57.
* [`src/custom-request.js`](diffhunk://#diff-3d024b2982939484b878c8446a661b479428d7e4bc40a72140164c7ef7ce0cb9R37-R52): Added logic to set the `mode` property to "cors" by default if not specified, ensuring …

fix: Ensure Response#mode is 'cors' when Request#type is 'cors'

---

src/fetch-mocker.js
tests/fetch-mocker.test.js

This pull request implements ["same-origin" mode](https://developer.mozilla.org/en-US/docs/Web/API/RequestInit#mode) mocking for `fetch()`. This ensures that requests like this correctly fail when making a cross-origin request:
```js
const response = await fetch("https://example.com/foo", { mode: "same-origin" });
```
The correct behavior is to throw a `TypeError` for any URLs that are not of the same origin.
* Added a check for `same-origin` mode in the `FetchMocker` class to throw a `TypeError` if the request origin does not match the URL's origin.
* Added a new test case to ensure a `TypeError` is thrown when a request with `mode=same-origin` is made to a different origin.
* Added a new test case to verify that a request with `mode=same-origin` succeeds when the request origin matches …

feat: Implement fetch with mode: "same-origin"

---

src/request-matcher.js
tests/request-matcher.test.js

This pull request improves the `RequestMatcher` class to handle URL patterns more robustly and adds comprehensive tests to ensure the new behavior is correct. The most important changes include modifying the URL pattern handling logic and adding multiple test cases to cover various scenarios.
URLPattern treats a leading slash as being an absolute path from the domain in the base URL (if present). So if the URL is /api and the base URL is https://example.com/v1, the URLPattern will match https://example.com/api. To avoid this, we remove the leading slash from the URL if it's present and add a trailing slash to the base URL if it's not present.
Enhancements to URL pattern handling:
* [`src/request-matcher.js`](diffhunk://#diff-a93d71985d250aedffbf5ca474e5df23cf3e882b3de1ea4cd1d5967f72ddf1d8L …

fix: Ensure baseUrl is properly applied to route matching

---

src/index.js

I would like to use the `RequestPattern`  type as part of my test utils. Seems like exporting the types file could be nice for other folks too. 
Other alternatives might be tweaking the package.json to expose the type file in the exports. Thanks for the awesome repo, I am really liking it.

feat: export types for use downstream

---

src/fetch-mocker.js
tests/fetch-mocker.test.js

Previously, when there were no partial matches found the error message would say "Partial matches found: No partial matches". This shortens it to just "No partial matches."
* [`src/fetch-mocker.js`](diffhunk://#diff-09d3018654f9d696c2ce0a5938eb9b5dd6adb822704efafcbfde8b6342f246c5L52-R55): Changed the message to "No partial matches found." when `traces.length` is zero, and adjusted the formatting of partial match messages. [[1]](diffhunk://#diff-09d3018654f9d696c2ce0a5938eb9b5dd6adb822704efafcbfde8b6342f246c5L52-R55) [[2]](diffhunk://#diff-09d3018654f9d696c2ce0a5938eb9b5dd6adb822704efafcbfde8b6342f246c5L65-R66)
Updates to test cases:
* [`tests/fetch-mocker.test.js`](diffhunk://#diff-c7749aa975a360a952d495ce66db5a38c09de5fa882d6cf00f2a86949208c1b9L36-L37): Updated the test case to reflect …

fix: More succinct message when no partial matches found

---

src/mock-server.js
tests/mock-server.test.js

This adds the ability for Mentoss to check already-called routes in addition to uncalled routes. This helps when a request is meant to match a route that has been registered, but doesn't because the route already matched a previous request, removing it from consideration.
When there isn't a match in uncalled routes, MockServer will now continue on to check called routes and return any that match with the note that it has already been matched and that's why it's not used.
Enhancements to tracing functionality:
* [`src/mock-server.js`](diffhunk://#diff-5024b7448f56bf978cf6ef5e933780ebabaf2d2977e6650c3c4df42c484245c4R553-R568): Added logic to check if any called routes match the request and produce a trace for each of them, including a message indicating that the route was already called. …

feat: Match against already-called routes for better errors

---

src/mock-server.js
tests/mock-server.test.js

This pull request includes changes to the `src/mock-server.js` and `tests/mock-server.test.js` files to improve the handling and testing of response bodies in the mock server.
fixes #89
Improvements to response body handling:
* [`src/mock-server.js`](diffhunk://#diff-5024b7448f56bf978cf6ef5e933780ebabaf2d2977e6650c3c4df42c484245c4L259-R259): Modified the condition to check if the body is a plain object by adding an additional check for the constructor property.
Enhancements to testing:
* [`tests/mock-server.test.js`](diffhunk://#diff-8ea18cf1c7d7bb1ad2967a064ede011cc0f2b983f81dc73877857d6b379049dfR275-R296): Added a new test case to verify that the mock server correctly returns an `ArrayBuffer` when the response body is an `ArrayBuffer`.

fix: Ensure ArrayBuffer is passed throughto response

---

src/custom-request.js
src/fetch-mocker.js
src/http.js
tests/custom-request.test.js
tests/redirect.test.js

This pull request enhances the `FetchMocker` class in `src/fetch-mocker.js` to add robust support for handling HTTP redirects in compliance with the fetch specification. It introduces new utility functions in `src/http.js` for redirect and method handling, and implements a private `#processRedirect` method to manage redirect chains. Additionally, it includes utility functions for working with HTTP status codes and methods.
fixes #77
* **Added `#processRedirect` method**: Implements recursive handling of HTTP redirects, including support for redirect modes (`manual`, `error`, `follow`), cross-origin redirects, and redirect chain limits. This ensures compliance with the fetch specification.
* **Introduced `createOpaqueRedirectResponse` function**: Creates opaque redirect responses for …

feat: Implement fetch redirects

---

src/custom-request.js
src/fetch-mocker.js
tests/custom-request.test.js
tests/redirect.test.js

By creating the fetch function in the constructor, we allocate a new function every time the mocker is instantiated.
We can avoid this by using a field (to bind `this`) which itself delegates to a method on the prototype.

chore: reuse fetch method

---

docs/src/content/docs/fetch-mockers/mocking-browser-requests.mdx
src/cookie-credentials.js
tests/cookie-credentials.test.js

This pull request introduces support for the `SameSite` attribute in cookies, making Mentoss work more similarly to browsers for better testing of CORS requests.
* Added support for the `SameSite` attribute in the `Cookie` class, with valid values being `"strict"`, `"lax"`, and `"none"`. The default is set to `"lax"`. (`[[1]](diffhunk://#diff-45b6751f6740be1d29980f701f3f438f5211ecde42697d68aecc6ce6537fa45bR32-R40)`, `[[2]](diffhunk://#diff-45b6751f6740be1d29980f701f3f438f5211ecde42697d68aecc6ce6537fa45bR115-R120)`, `[[3]](diffhunk://#diff-45b6751f6740be1d29980f701f3f438f5211ecde42697d68aecc6ce6537fa45bR130)`, `[[4]](diffhunk://#diff-45b6751f6740be1d29980f701f3f438f5211ecde42697d68aecc6ce6537fa45bR139)`, `[[5]](diffhunk://#diff-45b6751f6740be1d29980f701f3f438f5211ecde42697d68aecc6ce6537fa45 …

feat: Implement SameSite for cookies

---

src/fetch-mocker.js
src/util.js
tests/fetch-mocker.test.js
tests/util.test.js

This pull request refactors error handling in the `FetchMocker` module by introducing a new `NoRouteMatchedError` class to replace the previous inline error message formatting. It also updates the corresponding tests to validate the new error class.
* Replaced the `formatNoRouteMatchedMessage` function in `src/fetch-mocker.js` with a new `NoRouteMatchedError` class in `src/util.js`. This class encapsulates error details, including the request, body, and traces, and formats the error message. (`[[1]](diffhunk://#diff-09d3018654f9d696c2ce0a5938eb9b5dd6adb822704efafcbfde8b6342f246c5L12-R12)`, `[[2]](diffhunk://#diff-09d3018654f9d696c2ce0a5938eb9b5dd6adb822704efafcbfde8b6342f246c5L47-L78)`, `[[3]](diffhunk://#diff-9c0ec1b0a889e599f3ff81590864dd9dc65684a86b41f1da75acc53fafed12e3R73-R114)`)
* …

refactor: Create NoRouteMatchedError
